- name: Adding Python
  shell: |
    sudo apt-get install python-minimal -y

- name: "install node 12.X"
  shell: |
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt -y upgrade
    sudo apt install -y nodejs
- name: "install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: "copy files from CircleCI to server"
#   copy:
#     src: ~/backend
#     dest: /home/ubuntu
- name: Make backend dir
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "copy backend build"
  unarchive:
    src: /tmp/saveme/backend.tar.gz
    dest: /home/ubuntu/backend/

- name: "copy backend package.json"
  copy:
    src: /tmp/saveme/package.json
    dest: /home/ubuntu/backend/

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install

- name: "Set environment variables"
  become: yes
  shell: |
    echo "ENVIRONMENT=production" >> /etc/environment
    echo "TYPEORM_CONNECTION=postgres" >> /etc/environment
    echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> /etc/environment
    echo "TYPEORM_HOST=udacity.cn6hugvqdodg.us-west-2.rds.amazonaws.com" >> /etc/environment
    echo "TYPEORM_PORT=5432" >> /etc/environment
    echo "TYPEORM_USERNAME=postgres" >> /etc/environment
    echo "TYPEORM_PASSWORD=password" >> /etc/environment
    echo "TYPEORM_DATABASE=udacity" >> /etc/environment
