---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create directory
  file:
    path: ./dist
    state: directory

- name: "Set environment variables"
  become: yes
  shell: |
    echo "ENVIRONMENT=production" >> /etc/environment
    echo "TYPEORM_CONNECTION=postgres" >> /etc/environment
    echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> /etc/environment
    echo "TYPEORM_HOST=udacity.cn6hugvqdodg.us-west-2.rds.amazonaws.com" >> /etc/environment
    echo "TYPEORM_PORT=5432" >> /etc/environment
    echo "TYPEORM_USERNAME=postgres" >> /etc/environment
    echo "TYPEORM_PASSWORD=password" >> /etc/environment
    echo "TYPEORM_DATABASE=udacity" >> /etc/environment
